using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Model.Entities.Addresses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.SeedData;

public class CitySeedData : IEntityTypeConfiguration<City>
{
    public void Configure(EntityTypeBuilder<City> builder)
    {

        builder.HasData(

            new City { Id = 1, CityName = "کشکساری", ProvinceId = 1 },
            new City { Id = 2, CityName = "سهند", ProvinceId = 1 },
            new City { Id = 3, CityName = "سیس", ProvinceId = 1 },
            new City { Id = 4, CityName = "دوزدوزان", ProvinceId = 1 },
            new City { Id = 5, CityName = "تیمورلو", ProvinceId = 1 },
            new City { Id = 6, CityName = "صوفیان", ProvinceId = 1 },
            new City { Id = 7, CityName = "سردرود", ProvinceId = 1 },
            new City { Id = 8, CityName = "هادیشهر", ProvinceId = 1 },
            new City { Id = 9, CityName = "هشترود", ProvinceId = 1 },
            new City { Id = 10, CityName = "زرنق", ProvinceId = 1 },
            new City { Id = 11, CityName = "ترکمانچای", ProvinceId = 1 },
            new City { Id = 12, CityName = "ورزقان", ProvinceId = 1 },
            new City { Id = 13, CityName = "تسوج", ProvinceId = 1 },
            new City { Id = 14, CityName = "زنوز", ProvinceId = 1 },
            new City { Id = 15, CityName = "ایلخچی", ProvinceId = 1 },
            new City { Id = 16, CityName = "شرفانه", ProvinceId = 1 },
            new City { Id = 17, CityName = "مهربان", ProvinceId = 1 },
            new City { Id = 18, CityName = "مبارک شهر", ProvinceId = 1 },
            new City { Id = 19, CityName = "تیکمه داش", ProvinceId = 1 },
            new City { Id = 20, CityName = "باسمنج", ProvinceId = 1 },
            new City { Id = 21, CityName = "سیه رود", ProvinceId = 1 },
            new City { Id = 22, CityName = "میانه", ProvinceId = 1 },
            new City { Id = 23, CityName = "خمارلو", ProvinceId = 1 },
            new City { Id = 24, CityName = "خواجه", ProvinceId = 1 },
            new City { Id = 25, CityName = "بناب مرند", ProvinceId = 1 },
            new City { Id = 26, CityName = "قره آغاج", ProvinceId = 1 },
            new City { Id = 27, CityName = "وایقان", ProvinceId = 1 },
            new City { Id = 28, CityName = "مراغه", ProvinceId = 1 },
            new City { Id = 29, CityName = "ممقان", ProvinceId = 1 },
            new City { Id = 30, CityName = "خامنه", ProvinceId = 1 },
            new City { Id = 31, CityName = "خسروشاه", ProvinceId = 1 },
            new City { Id = 32, CityName = "لیلان", ProvinceId = 1 },
            new City { Id = 33, CityName = "نظرکهریزی", ProvinceId = 1 },
            new City { Id = 34, CityName = "اهر", ProvinceId = 1 },
            new City { Id = 35, CityName = "بخشایش", ProvinceId = 1 },
            new City { Id = 36, CityName = "آقکند", ProvinceId = 1 },
            new City { Id = 37, CityName = "جوان قلعه", ProvinceId = 1 },
            new City { Id = 38, CityName = "کلیبر", ProvinceId = 1 },
            new City { Id = 39, CityName = "مرند", ProvinceId = 1 },
            new City { Id = 40, CityName = "اسکو", ProvinceId = 1 },
            new City { Id = 41, CityName = "شندآباد", ProvinceId = 1 },
            new City { Id = 42, CityName = "شربیان", ProvinceId = 1 },
            new City { Id = 43, CityName = "گوگان", ProvinceId = 1 },
            new City { Id = 44, CityName = "بستان آباد", ProvinceId = 1 },
            new City { Id = 45, CityName = "تبریز", ProvinceId = 1 },
            new City { Id = 46, CityName = "جلفا", ProvinceId = 1 },
            new City { Id = 47, CityName = "اچاچی", ProvinceId = 1 },
            new City { Id = 48, CityName = "هریس", ProvinceId = 1 },
            new City { Id = 49, CityName = "یامچی", ProvinceId = 1 },
            new City { Id = 50, CityName = "خاروانا", ProvinceId = 1 },
            new City { Id = 51, CityName = "کوزه کنان", ProvinceId = 1 },
            new City { Id = 52, CityName = "خداجو", ProvinceId = 1 },
            new City { Id = 53, CityName = "آذرشهر", ProvinceId = 1 },
            new City { Id = 54, CityName = "شبستر", ProvinceId = 1 },
            new City { Id = 55, CityName = "سراب", ProvinceId = 1 },
            new City { Id = 56, CityName = "ملکان", ProvinceId = 1 },
            new City { Id = 57, CityName = "بناب", ProvinceId = 1 },
            new City { Id = 58, CityName = "هوراند", ProvinceId = 1 },
            new City { Id = 59, CityName = "کلوانق", ProvinceId = 1 },
            new City { Id = 60, CityName = "ترک", ProvinceId = 1 },
            new City { Id = 61, CityName = "عجب شیر", ProvinceId = 1 },
            new City { Id = 62, CityName = "آبش احمد", ProvinceId = 1 },
            new City { Id = 63, CityName = "تازه شهر", ProvinceId = 2 },
            new City { Id = 64, CityName = "نالوس", ProvinceId = 2 },
            new City { Id = 65, CityName = "ایواوغلی", ProvinceId = 2 },
            new City { Id = 66, CityName = "شاهین دژ", ProvinceId = 2 },
            new City { Id = 67, CityName = "گرد کشانه", ProvinceId = 2 },
            new City { Id = 68, CityName = "باروق", ProvinceId = 2 },
            new City { Id = 69, CityName = "سیلوانه", ProvinceId = 2 },
            new City { Id = 70, CityName = "بازرگان", ProvinceId = 2 },
            new City { Id = 71, CityName = "نازک علیا", ProvinceId = 2 },
            new City { Id = 72, CityName = "ربط", ProvinceId = 2 },
            new City { Id = 73, CityName = "تکاب", ProvinceId = 2 },
            new City { Id = 74, CityName = "دیزج دیز", ProvinceId = 2 },
            new City { Id = 75, CityName = "سیمینه", ProvinceId = 2 },
            new City { Id = 76, CityName = "نوشین", ProvinceId = 2 },
            new City { Id = 77, CityName = "میاندوآب", ProvinceId = 2 },
            new City { Id = 78, CityName = "مرگنلر", ProvinceId = 2 },
            new City { Id = 79, CityName = "سلماس", ProvinceId = 2 },
            new City { Id = 80, CityName = "آواجیق", ProvinceId = 2 },
            new City { Id = 81, CityName = "قطور", ProvinceId = 2 },
            new City { Id = 82, CityName = "محمود آباد", ProvinceId = 2 },
            new City { Id = 83, CityName = "خوی", ProvinceId = 2 },
            new City { Id = 84, CityName = "نقده", ProvinceId = 2 },
            new City { Id = 85, CityName = "سرو", ProvinceId = 2 },
            new City { Id = 86, CityName = "خلیفان", ProvinceId = 2 },
            new City { Id = 87, CityName = "پلدشت", ProvinceId = 2 },
            new City { Id = 88, CityName = "میر آباد", ProvinceId = 2 },
            new City { Id = 89, CityName = "اشنویه", ProvinceId = 2 },
            new City { Id = 90, CityName = "زرآباد", ProvinceId = 2 },
            new City { Id = 91, CityName = "بوکان", ProvinceId = 2 },
            new City { Id = 92, CityName = "پیرانشهر", ProvinceId = 2 },
            new City { Id = 93, CityName = "چهاربرج", ProvinceId = 2 },
            new City { Id = 94, CityName = "قوشچی", ProvinceId = 2 },
            new City { Id = 95, CityName = "شوط", ProvinceId = 2 },
            new City { Id = 96, CityName = "ماکو", ProvinceId = 2 },
            new City { Id = 97, CityName = "سیه چشمه", ProvinceId = 2 },
            new City { Id = 98, CityName = "سردشت", ProvinceId = 2 },
            new City { Id = 99, CityName = "کشاورز", ProvinceId = 2 },
            new City { Id = 100, CityName = "فیروق", ProvinceId = 2 },
            new City { Id = 101, CityName = "محمدیار", ProvinceId = 2 },
            new City { Id = 102, CityName = "ارومیه", ProvinceId = 2 },
            new City { Id = 103, CityName = "مهاباد", ProvinceId = 2 },
            new City { Id = 104, CityName = "قره ضیاءالدین", ProvinceId = 2 },
            new City { Id = 105, CityName = "پارس آباد", ProvinceId = 3 },
            new City { Id = 106, CityName = "فخر آباد", ProvinceId = 3 },
            new City { Id = 107, CityName = "کلور", ProvinceId = 3 },
            new City { Id = 108, CityName = "نیر", ProvinceId = 3 },
            new City { Id = 109, CityName = "اردبیل", ProvinceId = 3 },
            new City { Id = 110, CityName = "اسلام آباد", ProvinceId = 3 },
            new City { Id = 111, CityName = "تازه کندانگوت", ProvinceId = 3 },
            new City { Id = 112, CityName = "مشکین شهر", ProvinceId = 3 },
            new City { Id = 113, CityName = "جعفر اباد", ProvinceId = 3 },
            new City { Id = 114, CityName = "مرادلو", ProvinceId = 3 },
            new City { Id = 115, CityName = "خلخال", ProvinceId = 3 },
            new City { Id = 116, CityName = "نمین", ProvinceId = 3 },
            new City { Id = 117, CityName = "اصلاندوز", ProvinceId = 3 },
            new City { Id = 118, CityName = "کوراییم", ProvinceId = 3 },
            new City { Id = 119, CityName = "هیر", ProvinceId = 3 },
            new City { Id = 120, CityName = "گیوی", ProvinceId = 3 },
            new City { Id = 121, CityName = "گرمی", ProvinceId = 3 },
            new City { Id = 122, CityName = "لاهرود", ProvinceId = 3 },
            new City { Id = 123, CityName = "هشتجین", ProvinceId = 3 },
            new City { Id = 124, CityName = "عنبران", ProvinceId = 3 },
            new City { Id = 125, CityName = "تازهکند", ProvinceId = 3 },
            new City { Id = 126, CityName = "قصابه", ProvinceId = 3 },
            new City { Id = 127, CityName = "رضی", ProvinceId = 3 },
            new City { Id = 128, CityName = "سرعین", ProvinceId = 3 },
            new City { Id = 129, CityName = "بیله سوار", ProvinceId = 3 },
            new City { Id = 130, CityName = "آبی بیگلو", ProvinceId = 3 },
            new City { Id = 131, CityName = "گزبر خوار", ProvinceId = 4 },
            new City { Id = 132, CityName = "زیار", ProvinceId = 4 },
            new City { Id = 133, CityName = "زرین شهر", ProvinceId = 4 },
            new City { Id = 134, CityName = "گلشن", ProvinceId = 4 },
            new City { Id = 135, CityName = "پیربکران", ProvinceId = 4 },
            new City { Id = 136, CityName = "خالدآباد", ProvinceId = 4 },
            new City { Id = 137, CityName = "سجزی", ProvinceId = 4 },
            new City { Id = 138, CityName = "گوگد", ProvinceId = 4 },
            new City { Id = 139, CityName = "تیران", ProvinceId = 4 },
            new City { Id = 140, CityName = "ونک", ProvinceId = 4 },
            new City { Id = 141, CityName = "دهق", ProvinceId = 4 },
            new City { Id = 142, CityName = "زواره", ProvinceId = 4 },
            new City { Id = 143, CityName = "کاشان", ProvinceId = 4 },
            new City { Id = 144, CityName = "ابوزیدآباد", ProvinceId = 4 },
            new City { Id = 145, CityName = "اصغرآباد", ProvinceId = 4 },
            new City { Id = 146, CityName = "بافران", ProvinceId = 4 },
            new City { Id = 147, CityName = "شهرضا", ProvinceId = 4 },
            new City { Id = 148, CityName = "خور", ProvinceId = 4 },
            new City { Id = 149, CityName = "مجلسی", ProvinceId = 4 },
            new City { Id = 150, CityName = "هرند", ProvinceId = 4 },
            new City { Id = 151, CityName = "فولادشهر", ProvinceId = 4 },
            new City { Id = 152, CityName = "کمشچه", ProvinceId = 4 },
            new City { Id = 153, CityName = "کلیشادوسودرجان", ProvinceId = 4 },
            new City { Id = 154, CityName = "لای بید", ProvinceId = 4 },
            new City { Id = 155, CityName = "قهجاورستان", ProvinceId = 4 },
            new City { Id = 156, CityName = "چرمهین", ProvinceId = 4 },
            new City { Id = 157, CityName = "رزوه", ProvinceId = 4 },
            new City { Id = 158, CityName = "فریدونشهر", ProvinceId = 4 },
            new City { Id = 159, CityName = "طرقق رود", ProvinceId = 4 },
            new City { Id = 160, CityName = "نصرآباد", ProvinceId = 4 },
            new City { Id = 161, CityName = "برزک", ProvinceId = 4 },
            new City { Id = 162, CityName = "سفید شهر", ProvinceId = 4 },
            new City { Id = 163, CityName = "سمیرم", ProvinceId = 4 },
            new City { Id = 164, CityName = "گلدشت", ProvinceId = 4 },
            new City { Id = 165, CityName = "اردستان", ProvinceId = 4 },
            new City { Id = 166, CityName = "جوشقان قالی", ProvinceId = 4 },
            new City { Id = 167, CityName = "بویین و میاندشت", ProvinceId = 4 },
            new City { Id = 168, CityName = "کرکوند", ProvinceId = 4 },
            new City { Id = 169, CityName = "درچه", ProvinceId = 4 },
            new City { Id = 170, CityName = "انارک", ProvinceId = 4 },
            new City { Id = 171, CityName = "دولت اباد", ProvinceId = 4 },
            new City { Id = 172, CityName = "ایمانشهر", ProvinceId = 4 },
            new City { Id = 173, CityName = "گرگاب", ProvinceId = 4 },
            new City { Id = 174, CityName = "حسن آباد", ProvinceId = 4 },
            new City { Id = 175, CityName = "ده لنجان", ProvinceId = 4 },
            new City { Id = 176, CityName = "حبیب آباد", ProvinceId = 4 },
            new City { Id = 177, CityName = "بهاران شهر", ProvinceId = 4 },
            new City { Id = 178, CityName = "میمه", ProvinceId = 4 },
            new City { Id = 179, CityName = "تو دشت", ProvinceId = 4 },
            new City { Id = 180, CityName = "گلشهر", ProvinceId = 4 },
            new City { Id = 181, CityName = "رضوانشهر", ProvinceId = 4 },
            new City { Id = 182, CityName = "داران", ProvinceId = 4 },
            new City { Id = 183, CityName = "علویجه", ProvinceId = 4 },
            new City { Id = 184, CityName = "نیک آباد", ProvinceId = 4 },
            new City { Id = 185, CityName = "مشکات", ProvinceId = 4 },
            new City { Id = 186, CityName = "آران و بیدگل", ProvinceId = 4 },
            new City { Id = 187, CityName = "خوانسار", ProvinceId = 4 },
            new City { Id = 188, CityName = "نجف آباد", ProvinceId = 4 },
            new City { Id = 189, CityName = "منظریه", ProvinceId = 4 },
            new City { Id = 190, CityName = "فرخی", ProvinceId = 4 },
            new City { Id = 191, CityName = "دیزیچه", ProvinceId = 4 },
            new City { Id = 192, CityName = "اژیه", ProvinceId = 4 },
            new City { Id = 193, CityName = "زاینده رود", ProvinceId = 4 },
            new City { Id = 194, CityName = "خورزوق", ProvinceId = 4 },
            new City { Id = 195, CityName = "قهدریجان", ProvinceId = 4 },
            new City { Id = 196, CityName = "شاهین شهر", ProvinceId = 4 },
            new City { Id = 197, CityName = "بهارستان", ProvinceId = 4 },
            new City { Id = 198, CityName = "چمگردان", ProvinceId = 4 },
            new City { Id = 199, CityName = "دهاقان", ProvinceId = 4 },
            new City { Id = 200, CityName = "برف انبار", ProvinceId = 4 },
            new City { Id = 201, CityName = "بادرود", ProvinceId = 4 },
            new City { Id = 202, CityName = "کوهپایه", ProvinceId = 4 },
            new City { Id = 203, CityName = "گلپایگان", ProvinceId = 4 },
            new City { Id = 204, CityName = "عسگران", ProvinceId = 4 },
            new City { Id = 205, CityName = "حنا", ProvinceId = 4 },
            new City { Id = 206, CityName = "کهریزک", ProvinceId = 4 },
            new City { Id = 207, CityName = "مهاباد", ProvinceId = 4 },
            new City { Id = 208, CityName = "کامو چوگان", ProvinceId = 4 },
            new City { Id = 209, CityName = "افوس", ProvinceId = 4 },
            new City { Id = 210, CityName = "زیبا شهر", ProvinceId = 4 },
            new City { Id = 211, CityName = "کوشک", ProvinceId = 4 },
            new City { Id = 212, CityName = "نایین", ProvinceId = 4 },
            new City { Id = 213, CityName = "سین", ProvinceId = 4 },
            new City { Id = 214, CityName = "زازران", ProvinceId = 4 },
            new City { Id = 215, CityName = "مبارکه", ProvinceId = 4 },
            new City { Id = 216, CityName = "ورزنه", ProvinceId = 4 },
            new City { Id = 217, CityName = "ورنامخواست", ProvinceId = 4 },
            new City { Id = 218, CityName = "شاپور آباد", ProvinceId = 4 },
            new City { Id = 219, CityName = "فلاورجان", ProvinceId = 4 },
            new City { Id = 220, CityName = "وزوان", ProvinceId = 4 },
            new City { Id = 221, CityName = "اصفهان", ProvinceId = 4 },
            new City { Id = 222, CityName = "باغ بهادران", ProvinceId = 4 },
            new City { Id = 223, CityName = "چادگان", ProvinceId = 4 },
            new City { Id = 224, CityName = "دامنه", ProvinceId = 4 },
            new City { Id = 225, CityName = "نطنز", ProvinceId = 4 },
            new City { Id = 226, CityName = "محمد آباد", ProvinceId = 4 },
            new City { Id = 227, CityName = "نیاسر", ProvinceId = 4 },
            new City { Id = 228, CityName = "نوش آباد", ProvinceId = 4 },
            new City { Id = 229, CityName = "کمه", ProvinceId = 4 },
            new City { Id = 230, CityName = "جوزدان", ProvinceId = 4 },
            new City { Id = 231, CityName = "قمصر", ProvinceId = 4 },
            new City { Id = 232, CityName = "جندق", ProvinceId = 4 },
            new City { Id = 233, CityName = "طالخونچه", ProvinceId = 4 },
            new City { Id = 234, CityName = "خمینی شهر", ProvinceId = 4 },
            new City { Id = 235, CityName = "باغشاد", ProvinceId = 4 },
            new City { Id = 236, CityName = "دستگرد", ProvinceId = 4 },
            new City { Id = 237, CityName = "ابریشم", ProvinceId = 4 },
            new City { Id = 238, CityName = "چهارباغ", ProvinceId = 5 },
            new City { Id = 239, CityName = "آسارا", ProvinceId = 5 },
            new City { Id = 240, CityName = "کرج", ProvinceId = 5 },
            new City { Id = 241, CityName = "طالقان", ProvinceId = 5 },
            new City { Id = 242, CityName = "شهرجدیدهشتگرد", ProvinceId = 5 },
            new City { Id = 243, CityName = "محمدشهر", ProvinceId = 5 },
            new City { Id = 244, CityName = "مشکین دشت", ProvinceId = 5 },
            new City { Id = 245, CityName = "نظرآباد", ProvinceId = 5 },
            new City { Id = 246, CityName = "هشتگرد", ProvinceId = 5 },
            new City { Id = 247, CityName = "ماهدشت", ProvinceId = 5 },
            new City { Id = 248, CityName = "اشتهارد", ProvinceId = 5 },
            new City { Id = 249, CityName = "کوهسار", ProvinceId = 5 },
            new City { Id = 250, CityName = "گرمدره", ProvinceId = 5 },
            new City { Id = 251, CityName = "تنکمان", ProvinceId = 5 },
            new City { Id = 252, CityName = "گلسار", ProvinceId = 5 },
            new City { Id = 253, CityName = "کمالشهر", ProvinceId = 5 },
            new City { Id = 254, CityName = "فردیس", ProvinceId = 5 },
            new City { Id = 255, CityName = "آبدانان", ProvinceId = 6 },
            new City { Id = 256, CityName = "شباب", ProvinceId = 6 },
            new City { Id = 257, CityName = "موسیان", ProvinceId = 6 },
            new City { Id = 258, CityName = "بدره", ProvinceId = 6 },
            new City { Id = 259, CityName = "ایلام", ProvinceId = 6 },
            new City { Id = 260, CityName = "ایوان", ProvinceId = 6 },
            new City { Id = 261, CityName = "مهران", ProvinceId = 6 },
            new City { Id = 262, CityName = "آسمان آباد", ProvinceId = 6 },
            new City { Id = 263, CityName = "پهله", ProvinceId = 6 },
            new City { Id = 264, CityName = "مهر", ProvinceId = 6 },
            new City { Id = 265, CityName = "سراب باغ", ProvinceId = 6 },
            new City { Id = 266, CityName = "بلاوه", ProvinceId = 6 },
            new City { Id = 267, CityName = "میمه", ProvinceId = 6 },
            new City { Id = 268, CityName = "دره شهر", ProvinceId = 6 },
            new City { Id = 269, CityName = "ارکواز", ProvinceId = 6 },
            new City { Id = 270, CityName = "مورموری", ProvinceId = 6 },
            new City { Id = 271, CityName = "توحید", ProvinceId = 6 },
            new City { Id = 272, CityName = "دهلران", ProvinceId = 6 },
            new City { Id = 273, CityName = "لومار", ProvinceId = 6 },
            new City { Id = 274, CityName = "چوار", ProvinceId = 6 },
            new City { Id = 275, CityName = "زرنه", ProvinceId = 6 },
            new City { Id = 276, CityName = "صالح آباد", ProvinceId = 6 },
            new City { Id = 277, CityName = "سرابله", ProvinceId = 6 },
            new City { Id = 278, CityName = "ماژین", ProvinceId = 6 },
            new City { Id = 279, CityName = "دلگشا", ProvinceId = 6 },
            new City { Id = 280, CityName = "ریز", ProvinceId = 7 },
            new City { Id = 281, CityName = "برازجان", ProvinceId = 7 },
            new City { Id = 282, CityName = "بندریگ", ProvinceId = 7 },
            new City { Id = 283, CityName = "اهرم", ProvinceId = 7 },
            new City { Id = 284, CityName = "دوراهک", ProvinceId = 7 },
            new City { Id = 285, CityName = "خورموج", ProvinceId = 7 },
            new City { Id = 286, CityName = "نخل تقی", ProvinceId = 7 },
            new City { Id = 287, CityName = "کلمه", ProvinceId = 7 },
            new City { Id = 288, CityName = "بندر دیلم", ProvinceId = 7 },
            new City { Id = 289, CityName = "وحدتیه", ProvinceId = 7 },
            new City { Id = 290, CityName = "بنک", ProvinceId = 7 },
            new City { Id = 291, CityName = "چغادک", ProvinceId = 7 },
            new City { Id = 292, CityName = "بندر دیر", ProvinceId = 7 },
            new City { Id = 293, CityName = "کاکی", ProvinceId = 7 },
            new City { Id = 294, CityName = "جم", ProvinceId = 7 },
            new City { Id = 295, CityName = "دالکی", ProvinceId = 7 },
            new City { Id = 296, CityName = "بندرگناوه", ProvinceId = 7 },
            new City { Id = 297, CityName = "آبدان", ProvinceId = 7 },
            new City { Id = 298, CityName = "خارک", ProvinceId = 7 },
            new City { Id = 299, CityName = "شنبه", ProvinceId = 7 },
            new City { Id = 300, CityName = "بوشکان", ProvinceId = 7 },
            new City { Id = 301, CityName = "انارستان", ProvinceId = 7 },
            new City { Id = 302, CityName = "شبانکاره", ProvinceId = 7 },
            new City { Id = 303, CityName = "سیراف", ProvinceId = 7 },
            new City { Id = 304, CityName = "دلوار", ProvinceId = 7 },
            new City { Id = 305, CityName = "بردستان", ProvinceId = 7 },
            new City { Id = 306, CityName = "بادوله", ProvinceId = 7 },
            new City { Id = 307, CityName = "عسلویه", ProvinceId = 7 },
            new City { Id = 308, CityName = "تنگ ارم", ProvinceId = 7 },
            new City { Id = 309, CityName = "امام حسن", ProvinceId = 7 },
            new City { Id = 310, CityName = "سعد آباد", ProvinceId = 7 },
            new City { Id = 311, CityName = "بندرکنگان", ProvinceId = 7 },
            new City { Id = 312, CityName = "بوشهر", ProvinceId = 7 },
            new City { Id = 313, CityName = "بردخون", ProvinceId = 7 },
            new City { Id = 314, CityName = "آب پخش", ProvinceId = 7 },
            new City { Id = 315, CityName = "شاهدشهر", ProvinceId = 8 },
            new City { Id = 316, CityName = "پیشوا", ProvinceId = 8 },
            new City { Id = 317, CityName = "جواد آباد", ProvinceId = 8 },
            new City { Id = 318, CityName = "ارجمند", ProvinceId = 8 },
            new City { Id = 319, CityName = "ری", ProvinceId = 8 },
            new City { Id = 320, CityName = "نصیرشهر", ProvinceId = 8 },
            new City { Id = 321, CityName = "رودهن", ProvinceId = 8 },
            new City { Id = 322, CityName = "اندیشه", ProvinceId = 8 },
            new City { Id = 323, CityName = "نسیم شهر", ProvinceId = 8 },
            new City { Id = 324, CityName = "صباشهر", ProvinceId = 8 },
            new City { Id = 325, CityName = "ملارد", ProvinceId = 8 },
            new City { Id = 326, CityName = "شمشک", ProvinceId = 8 },
            new City { Id = 327, CityName = "پاکدشت", ProvinceId = 8 },
            new City { Id = 328, CityName = "باقر شهر", ProvinceId = 8 },
            new City { Id = 329, CityName = "احمد آباد مستوفی", ProvinceId = 8 },
            new City { Id = 330, CityName = "کیلان", ProvinceId = 8 },
            new City { Id = 331, CityName = "قرچک", ProvinceId = 8 },
            new City { Id = 332, CityName = "فردوسیه", ProvinceId = 8 },
            new City { Id = 333, CityName = "گلستان", ProvinceId = 8 },
            new City { Id = 334, CityName = "ورامین", ProvinceId = 8 },
            new City { Id = 335, CityName = "فیروزکوه", ProvinceId = 8 },
            new City { Id = 336, CityName = "فشم", ProvinceId = 8 },
            new City { Id = 337, CityName = "پرند", ProvinceId = 8 },
            new City { Id = 338, CityName = "آبعلی", ProvinceId = 8 },
            new City { Id = 339, CityName = "چهاردانگه", ProvinceId = 8 },
            new City { Id = 340, CityName = "تهران", ProvinceId = 8 },
            new City { Id = 341, CityName = "بومهن", ProvinceId = 8 },
            new City { Id = 342, CityName = "وحیدیه", ProvinceId = 8 },
            new City { Id = 343, CityName = "صفادشت", ProvinceId = 8 },
            new City { Id = 344, CityName = "لواسان", ProvinceId = 8 },
            new City { Id = 345, CityName = "فرون اباد", ProvinceId = 8 },
            new City { Id = 346, CityName = "کهریزک", ProvinceId = 8 },
            new City { Id = 347, CityName = "رباطکریم", ProvinceId = 8 },
            new City { Id = 348, CityName = "آبسرد", ProvinceId = 8 },
            new City { Id = 349, CityName = "باغستان", ProvinceId = 8 },
            new City { Id = 350, CityName = "صالحیه", ProvinceId = 8 },
            new City { Id = 351, CityName = "شهریار", ProvinceId = 8 },
            new City { Id = 352, CityName = "قدس", ProvinceId = 8 },
            new City { Id = 353, CityName = "تجریش", ProvinceId = 8 },
            new City { Id = 354, CityName = "شریف آباد", ProvinceId = 8 },
            new City { Id = 355, CityName = "حسن آباد", ProvinceId = 8 },
            new City { Id = 356, CityName = "اسلامشهر", ProvinceId = 8 },
            new City { Id = 357, CityName = "دماوند", ProvinceId = 8 },
            new City { Id = 358, CityName = "پردیس", ProvinceId = 8 },
            new City { Id = 359, CityName = "وردنجان", ProvinceId = 9 },
            new City { Id = 360, CityName = "گوجان", ProvinceId = 9 },
            new City { Id = 361, CityName = "گهرو", ProvinceId = 9 },
            new City { Id = 362, CityName = "سورشجان", ProvinceId = 9 },
            new City { Id = 363, CityName = "سرخون", ProvinceId = 9 },
            new City { Id = 364, CityName = "شهرکرد", ProvinceId = 9 },
            new City { Id = 365, CityName = "منج", ProvinceId = 9 },
            new City { Id = 366, CityName = "بروجن", ProvinceId = 9 },
            new City { Id = 367, CityName = "پردنجان", ProvinceId = 9 },
            new City { Id = 368, CityName = "سامان", ProvinceId = 9 },
            new City { Id = 369, CityName = "فرخشهر", ProvinceId = 9 },
            new City { Id = 370, CityName = "صمصامی", ProvinceId = 9 },
            new City { Id = 371, CityName = "طاقانک", ProvinceId = 9 },
            new City { Id = 372, CityName = "کاج", ProvinceId = 9 },
            new City { Id = 373, CityName = "نقنه", ProvinceId = 9 },
            new City { Id = 374, CityName = "لردگان", ProvinceId = 9 },
            new City { Id = 375, CityName = "باباحیدر", ProvinceId = 9 },
            new City { Id = 376, CityName = "دستنا", ProvinceId = 9 },
            new City { Id = 377, CityName = "سودجان", ProvinceId = 9 },
            new City { Id = 378, CityName = "بازفت", ProvinceId = 9 },
            new City { Id = 379, CityName = "هفشجان", ProvinceId = 9 },
            new City { Id = 380, CityName = "سردشت", ProvinceId = 9 },
            new City { Id = 381, CityName = "فرادبنه", ProvinceId = 9 },
            new City { Id = 382, CityName = "چلیچه", ProvinceId = 9 },
            new City { Id = 383, CityName = "بن", ProvinceId = 9 },
            new City { Id = 384, CityName = "فارسان", ProvinceId = 9 },
            new City { Id = 385, CityName = "شلمزار", ProvinceId = 9 },
            new City { Id = 386, CityName = "نافچ", ProvinceId = 9 },
            new City { Id = 387, CityName = "دشتک", ProvinceId = 9 },
            new City { Id = 388, CityName = "بلداجی", ProvinceId = 9 },
            new City { Id = 389, CityName = "آلونی", ProvinceId = 9 },
            new City { Id = 390, CityName = "گندمان", ProvinceId = 9 },
            new City { Id = 391, CityName = "جونقان", ProvinceId = 9 },
            new City { Id = 392, CityName = "ناغان", ProvinceId = 9 },
            new City { Id = 393, CityName = "هارونی", ProvinceId = 9 },
            new City { Id = 394, CityName = "چلگرد", ProvinceId = 9 },
            new City { Id = 395, CityName = "کیان", ProvinceId = 9 },
            new City { Id = 396, CityName = "اردل", ProvinceId = 9 },
            new City { Id = 397, CityName = "سفید دشت", ProvinceId = 9 },
            new City { Id = 398, CityName = "مال خلیفه", ProvinceId = 9 },
            new City { Id = 399, CityName = "اسلامیه", ProvinceId = 10 },
            new City { Id = 400, CityName = "شوسف", ProvinceId = 10 },
            new City { Id = 401, CityName = "قاین", ProvinceId = 10 },
            new City { Id = 402, CityName = "عشقآباد", ProvinceId = 10 },
            new City { Id = 403, CityName = "طبس مسینا", ProvinceId = 10 },
            new City { Id = 404, CityName = "ارسک", ProvinceId = 10 },
            new City { Id = 405, CityName = "ایسک", ProvinceId = 10 },
            new City { Id = 406, CityName = "نیمبلوک", ProvinceId = 10 },
            new City { Id = 407, CityName = "دهوک", ProvinceId = 10 },
            new City { Id = 408, CityName = "سربیشه", ProvinceId = 10 },
            new City { Id = 409, CityName = "محمد شهر", ProvinceId = 10 },
            new City { Id = 410, CityName = "بیرجند", ProvinceId = 10 },
            new City { Id = 411, CityName = "فردوس", ProvinceId = 10 },
            new City { Id = 412, CityName = "نهبندان", ProvinceId = 10 },
            new City { Id = 413, CityName = "اسفدن", ProvinceId = 10 },
            new City { Id = 414, CityName = "گریزک", ProvinceId = 10 },
            new City { Id = 415, CityName = "حاجی آباد", ProvinceId = 10 },
            new City { Id = 416, CityName = "سه قلعه", ProvinceId = 10 },
            new City { Id = 417, CityName = "آرین شهر", ProvinceId = 10 },
            new City { Id = 418, CityName = "مود", ProvinceId = 10 },
            new City { Id = 419, CityName = "خوسف", ProvinceId = 10 },
            new City { Id = 420, CityName = "قهستان", ProvinceId = 10 },
            new City { Id = 421, CityName = "بشرویه", ProvinceId = 10 },
            new City { Id = 422, CityName = "سرایان", ProvinceId = 10 },
            new City { Id = 423, CityName = "خضری دشت بیاض", ProvinceId = 10 },
            new City { Id = 424, CityName = "طبس", ProvinceId = 10 },
            new City { Id = 425, CityName = "اسدیه", ProvinceId = 10 },
            new City { Id = 426, CityName = "زهان", ProvinceId = 10 },
            new City { Id = 427, CityName = "بار", ProvinceId = 11 },
            new City { Id = 428, CityName = "نیل شهر", ProvinceId = 11 },
            new City { Id = 429, CityName = "جنگل", ProvinceId = 11 },
            new City { Id = 430, CityName = "درود", ProvinceId = 11 },
            new City { Id = 431, CityName = "رباط سنگ", ProvinceId = 11 },
            new City { Id = 432, CityName = "سلطان آباد", ProvinceId = 11 },
            new City { Id = 433, CityName = "فریمان", ProvinceId = 11 },
            new City { Id = 434, CityName = "گناباد", ProvinceId = 11 },
            new City { Id = 435, CityName = "کاریز", ProvinceId = 11 },
            new City { Id = 436, CityName = "همت آباد", ProvinceId = 11 },
            new City { Id = 437, CityName = "سلامی", ProvinceId = 11 },
            new City { Id = 438, CityName = "باجگیران", ProvinceId = 11 },
            new City { Id = 439, CityName = "بجستان", ProvinceId = 11 },
            new City { Id = 440, CityName = "چناران", ProvinceId = 11 },
            new City { Id = 441, CityName = "درگز", ProvinceId = 11 },
            new City { Id = 442, CityName = "کلات", ProvinceId = 11 },
            new City { Id = 443, CityName = "چکنه", ProvinceId = 11 },
            new City { Id = 444, CityName = "نصرآباد", ProvinceId = 11 },
            new City { Id = 445, CityName = "بردسکن", ProvinceId = 11 },
            new City { Id = 446, CityName = "مشهد", ProvinceId = 11 },
            new City { Id = 447, CityName = "کدکن", ProvinceId = 11 },
            new City { Id = 448, CityName = "نقاب", ProvinceId = 11 },
            new City { Id = 449, CityName = "قلندر آباد", ProvinceId = 11 },
            new City { Id = 450, CityName = "کاشمر", ProvinceId = 11 },
            new City { Id = 451, CityName = "شاندیز", ProvinceId = 11 },
            new City { Id = 452, CityName = "نشتیفان", ProvinceId = 11 },
            new City { Id = 453, CityName = "ششتمد", ProvinceId = 11 },
            new City { Id = 454, CityName = "شادمهر", ProvinceId = 11 },
            new City { Id = 455, CityName = "عشق آباد", ProvinceId = 11 },
            new City { Id = 456, CityName = "چاپشلو", ProvinceId = 11 },
            new City { Id = 457, CityName = "رشتخوار", ProvinceId = 11 },
            new City { Id = 458, CityName = "قدمگاه", ProvinceId = 11 },
            new City { Id = 459, CityName = "صالح آباد", ProvinceId = 11 },
            new City { Id = 460, CityName = "داورزن", ProvinceId = 11 },
            new City { Id = 461, CityName = "فرهادگرد", ProvinceId = 11 },
            new City { Id = 462, CityName = "کاخک", ProvinceId = 11 },
            new City { Id = 463, CityName = "مشهدریزه", ProvinceId = 11 },
            new City { Id = 464, CityName = "جغتای", ProvinceId = 11 },
            new City { Id = 465, CityName = "مزدآوند", ProvinceId = 11 },
            new City { Id = 466, CityName = "قوچان", ProvinceId = 11 },
            new City { Id = 467, CityName = "یونسی", ProvinceId = 11 },
            new City { Id = 468, CityName = "سنگان", ProvinceId = 11 },
            new City { Id = 469, CityName = "نوخندان", ProvinceId = 11 },
            new City { Id = 470, CityName = "کندر", ProvinceId = 11 },
            new City { Id = 471, CityName = "نیشابور", ProvinceId = 11 },
            new City { Id = 472, CityName = "احمد آباد صولت", ProvinceId = 11 },
            new City { Id = 473, CityName = "شهر آباد", ProvinceId = 11 },
            new City { Id = 474, CityName = "رضویه", ProvinceId = 11 },
            new City { Id = 475, CityName = "تربت حیدریه", ProvinceId = 11 },
            new City { Id = 476, CityName = "باخرز", ProvinceId = 11 },
            new City { Id = 477, CityName = "سفیدسنگ", ProvinceId = 11 },
            new City { Id = 478, CityName = "بیدخت", ProvinceId = 11 },
            new City { Id = 479, CityName = "تایباد", ProvinceId = 11 },
            new City { Id = 480, CityName = "فیروزه", ProvinceId = 11 },
            new City { Id = 481, CityName = "قاسم آباد", ProvinceId = 11 },
            new City { Id = 482, CityName = "سبزوار", ProvinceId = 11 },
            new City { Id = 483, CityName = "فیض آباد", ProvinceId = 11 },
            new City { Id = 484, CityName = "گلمکان", ProvinceId = 11 },
            new City { Id = 485, CityName = "لطف آباد", ProvinceId = 11 },
            new City { Id = 486, CityName = "شهروز", ProvinceId = 11 },
            new City { Id = 487, CityName = "خرو", ProvinceId = 11 },
            new City { Id = 488, CityName = "تربت جام", ProvinceId = 11 },
            new City { Id = 489, CityName = "انابد", ProvinceId = 11 },
            new City { Id = 490, CityName = "ملک آباد", ProvinceId = 11 },
            new City { Id = 491, CityName = "بایک", ProvinceId = 11 },
            new City { Id = 492, CityName = "دولت آباد", ProvinceId = 11 },
            new City { Id = 493, CityName = "سرخس", ProvinceId = 11 },
            new City { Id = 494, CityName = "ریوش", ProvinceId = 11 },
            new City { Id = 495, CityName = "طرقبه", ProvinceId = 11 },
            new City { Id = 496, CityName = "خواف", ProvinceId = 11 },
            new City { Id = 497, CityName = "روداب", ProvinceId = 11 },
            new City { Id = 498, CityName = "خلیل آباد", ProvinceId = 11 },
            new City { Id = 499, CityName = "چناران شهر", ProvinceId = 11 },
            new City { Id = 500, CityName = "راز", ProvinceId = 12 },
            new City { Id = 501, CityName = "پیش قلعه", ProvinceId = 12 },
            new City { Id = 502, CityName = "قوشخانه", ProvinceId = 12 },
            new City { Id = 503, CityName = "شوقان", ProvinceId = 12 },
            new City { Id = 504, CityName = "اسفراین", ProvinceId = 12 },
            new City { Id = 505, CityName = "گرمه", ProvinceId = 12 },
            new City { Id = 506, CityName = "قاضی", ProvinceId = 12 },
            new City { Id = 507, CityName = "شیروان", ProvinceId = 12 },
            new City { Id = 508, CityName = "حسار گرمخان", ProvinceId = 12 },
            new City { Id = 509, CityName = "آشخانه", ProvinceId = 12 },
            new City { Id = 510, CityName = "تیتکانلو", ProvinceId = 12 },
            new City { Id = 511, CityName = "جاجرم", ProvinceId = 12 },
            new City { Id = 512, CityName = "بجنورد", ProvinceId = 12 },
            new City { Id = 513, CityName = "درق", ProvinceId = 12 },
            new City { Id = 514, CityName = "آوا", ProvinceId = 12 },
            new City { Id = 515, CityName = "زیارت", ProvinceId = 12 },
            new City { Id = 516, CityName = "سنخواست", ProvinceId = 12 },
            new City { Id = 517, CityName = "صفی آباد", ProvinceId = 12 },
            new City { Id = 518, CityName = "ایور", ProvinceId = 12 },
            new City { Id = 519, CityName = "فاروج", ProvinceId = 12 },
            new City { Id = 520, CityName = "لوجلی", ProvinceId = 12 },
            new City { Id = 521, CityName = "هفتگل", ProvinceId = 13 },
            new City { Id = 522, CityName = "بیدروبه", ProvinceId = 13 },
            new City { Id = 523, CityName = "شاوور", ProvinceId = 13 },
            new City { Id = 524, CityName = "حمزه", ProvinceId = 13 },
            new City { Id = 525, CityName = "گتوند", ProvinceId = 13 },
            new City { Id = 526, CityName = "شرافت", ProvinceId = 13 },
            new City { Id = 527, CityName = "منصوریه", ProvinceId = 13 },
            new City { Id = 528, CityName = "زهره", ProvinceId = 13 },
            new City { Id = 529, CityName = "رامهرمز", ProvinceId = 13 },
            new City { Id = 530, CityName = "بندرامام خمینی", ProvinceId = 13 },
            new City { Id = 531, CityName = "کوت عبدالله", ProvinceId = 13 },
            new City { Id = 532, CityName = "میداود", ProvinceId = 13 },
            new City { Id = 533, CityName = "چغامیش", ProvinceId = 13 },
            new City { Id = 534, CityName = "ملاثانی", ProvinceId = 13 },
            new City { Id = 535, CityName = "چم گلک", ProvinceId = 13 },
            new City { Id = 536, CityName = "حر", ProvinceId = 13 },
            new City { Id = 537, CityName = "شمس آباد", ProvinceId = 13 },
            new City { Id = 538, CityName = "آبژدان", ProvinceId = 13 },
            new City { Id = 539, CityName = "چویبده", ProvinceId = 13 },
            new City { Id = 540, CityName = "مسجد سلیمان", ProvinceId = 13 },
            new City { Id = 541, CityName = "مقاومت", ProvinceId = 13 },
            new City { Id = 542, CityName = "ترکالکی", ProvinceId = 13 },
            new City { Id = 543, CityName = "دارخوین", ProvinceId = 13 },
            new City { Id = 544, CityName = "سردشت", ProvinceId = 13 },
            new City { Id = 545, CityName = "لالی", ProvinceId = 13 },
            new City { Id = 546, CityName = "کوت سیدنعیم", ProvinceId = 13 },
            new City { Id = 547, CityName = "حمیدیه", ProvinceId = 13 },
            new City { Id = 548, CityName = "دهدز", ProvinceId = 13 },
            new City { Id = 549, CityName = "قلعه تل", ProvinceId = 13 },
            new City { Id = 550, CityName = "میانرود", ProvinceId = 13 },
            new City { Id = 551, CityName = "رفیع", ProvinceId = 13 },
            new City { Id = 552, CityName = "اندیمشک", ProvinceId = 13 },
            new City { Id = 553, CityName = "الوان", ProvinceId = 13 },
            new City { Id = 554, CityName = "سالند", ProvinceId = 13 },
            new City { Id = 555, CityName = "صالح شهر", ProvinceId = 13 },
            new City { Id = 556, CityName = "اروندکنار", ProvinceId = 13 },
            new City { Id = 557, CityName = "سرداران", ProvinceId = 13 },
            new City { Id = 558, CityName = "تشان", ProvinceId = 13 },
            new City { Id = 559, CityName = "رامشیر", ProvinceId = 13 },
            new City { Id = 560, CityName = "شادگان", ProvinceId = 13 },
            new City { Id = 561, CityName = "بندر ماهشهر", ProvinceId = 13 },
            new City { Id = 562, CityName = "جایزان", ProvinceId = 13 },
            new City { Id = 563, CityName = "بستان", ProvinceId = 13 },
            new City { Id = 564, CityName = "ویس", ProvinceId = 13 },
            new City { Id = 565, CityName = "اهواز", ProvinceId = 13 },
            new City { Id = 566, CityName = "فتح المبین", ProvinceId = 13 },
            new City { Id = 567, CityName = "شهر امام", ProvinceId = 13 },
            new City { Id = 568, CityName = "قلعه خاجو", ProvinceId = 13 },
            new City { Id = 569, CityName = "حسینیه", ProvinceId = 13 },
            new City { Id = 570, CityName = "گلگیر", ProvinceId = 13 },
            new City { Id = 571, CityName = "مینوشهر", ProvinceId = 13 },
            new City { Id = 572, CityName = "سماله", ProvinceId = 13 },
            new City { Id = 573, CityName = "شوشتر", ProvinceId = 13 },
            new City { Id = 574, CityName = "بهبهان", ProvinceId = 13 },
            new City { Id = 575, CityName = "هندیجان", ProvinceId = 13 },
            new City { Id = 576, CityName = "ابوحمیظه", ProvinceId = 13 },
            new City { Id = 577, CityName = "آغاجاری", ProvinceId = 13 },
            new City { Id = 578, CityName = "ایذه", ProvinceId = 13 },
            new City { Id = 579, CityName = "صیدون", ProvinceId = 13 },
            new City { Id = 580, CityName = "سیاه منصور", ProvinceId = 13 },
            new City { Id = 581, CityName = "هویزه", ProvinceId = 13 },
            new City { Id = 582, CityName = "آزادی", ProvinceId = 13 },
            new City { Id = 583, CityName = "شوش", ProvinceId = 13 },
            new City { Id = 584, CityName = "دزفول", ProvinceId = 13 },
            new City { Id = 585, CityName = "جنت مکان", ProvinceId = 13 },
            new City { Id = 586, CityName = "آبادان", ProvinceId = 13 },
            new City { Id = 587, CityName = "گوریه", ProvinceId = 13 },
            new City { Id = 588, CityName = "خرمشهر", ProvinceId = 13 },
            new City { Id = 589, CityName = "مشراگه", ProvinceId = 13 },
            new City { Id = 590, CityName = "خنافره", ProvinceId = 13 },
            new City { Id = 591, CityName = "چمران", ProvinceId = 13 },
            new City { Id = 592, CityName = "امیدیه", ProvinceId = 13 },
            new City { Id = 593, CityName = "سوسنگرد", ProvinceId = 13 },
            new City { Id = 594, CityName = "شیبان", ProvinceId = 13 },
            new City { Id = 595, CityName = "الهایی", ProvinceId = 13 },
            new City { Id = 596, CityName = "باغ الملک", ProvinceId = 13 },
            new City { Id = 597, CityName = "صفی آباد", ProvinceId = 13 },
            new City { Id = 598, CityName = "سجاس", ProvinceId = 14 },
            new City { Id = 599, CityName = "زرین رود", ProvinceId = 14 },
            new City { Id = 600, CityName = "آب بر", ProvinceId = 14 },
            new City { Id = 601, CityName = "ارمغانخانه", ProvinceId = 14 },
            new City { Id = 602, CityName = "کرسف", ProvinceId = 14 },
            new City { Id = 603, CityName = "هیدج", ProvinceId = 14 },
            new City { Id = 604, CityName = "سلطانیه", ProvinceId = 14 },
            new City { Id = 605, CityName = "خرمدره", ProvinceId = 14 },
            new City { Id = 606, CityName = "نیک پی", ProvinceId = 14 },
            new City { Id = 607, CityName = "قیدار", ProvinceId = 14 },
            new City { Id = 608, CityName = "ابهر", ProvinceId = 14 },
            new City { Id = 609, CityName = "دندی", ProvinceId = 14 },
            new City { Id = 610, CityName = "حلب", ProvinceId = 14 },
            new City { Id = 611, CityName = "نوربهار", ProvinceId = 14 },
            new City { Id = 612, CityName = "گرماب", ProvinceId = 14 },
            new City { Id = 613, CityName = "چورزق", ProvinceId = 14 },
            new City { Id = 614, CityName = "زنجان", ProvinceId = 14 },
            new City { Id = 615, CityName = "سهرود", ProvinceId = 14 },
            new City { Id = 616, CityName = "صایین قلعه", ProvinceId = 14 },
            new City { Id = 617, CityName = "ماه نشان", ProvinceId = 14 },
            new City { Id = 618, CityName = "زرین آباد", ProvinceId = 14 },
            new City { Id = 619, CityName = "ایوانکی", ProvinceId = 15 },
            new City { Id = 620, CityName = "مجن", ProvinceId = 15 },
            new City { Id = 621, CityName = "دامغان", ProvinceId = 15 },
            new City { Id = 622, CityName = "سرخه", ProvinceId = 15 },
            new City { Id = 623, CityName = "مهدیشهر", ProvinceId = 15 },
            new City { Id = 624, CityName = "شاهرود", ProvinceId = 15 },
            new City { Id = 625, CityName = "سمنان", ProvinceId = 15 },
            new City { Id = 626, CityName = "کهن آباد", ProvinceId = 15 },
            new City { Id = 627, CityName = "گرمسار", ProvinceId = 15 },
            new City { Id = 628, CityName = "کلاته خیج", ProvinceId = 15 },
            new City { Id = 629, CityName = "دیباج", ProvinceId = 15 },
            new City { Id = 630, CityName = "درجزین", ProvinceId = 15 },
            new City { Id = 631, CityName = "رودیان", ProvinceId = 15 },
            new City { Id = 632, CityName = "بسطام", ProvinceId = 15 },
            new City { Id = 633, CityName = "امیریه", ProvinceId = 15 },
            new City { Id = 634, CityName = "میامی", ProvinceId = 15 },
            new City { Id = 635, CityName = "شهمیزاد", ProvinceId = 15 },
            new City { Id = 636, CityName = "بیارجمند", ProvinceId = 15 },
            new City { Id = 637, CityName = "کلاته", ProvinceId = 15 },
            new City { Id = 638, CityName = "آردان", ProvinceId = 15 },
            new City { Id = 639, CityName = "محمدی", ProvinceId = 16 },
            new City { Id = 640, CityName = "شهرک غلی اکبر", ProvinceId = 16 },
            new City { Id = 641, CityName = "بنجار", ProvinceId = 16 },
            new City { Id = 642, CityName = "گلمورتی", ProvinceId = 16 },
            new City { Id = 643, CityName = "نگور", ProvinceId = 16 },
            new City { Id = 644, CityName = "راسک", ProvinceId = 16 },
            new City { Id = 645, CityName = "بنت", ProvinceId = 16 },
            new City { Id = 646, CityName = "قصرقند", ProvinceId = 16 },
            new City { Id = 647, CityName = "جالق", ProvinceId = 16 },
            new City { Id = 648, CityName = "هیدوچ", ProvinceId = 16 },
            new City { Id = 649, CityName = "نوک آباد", ProvinceId = 16 },
            new City { Id = 650, CityName = "زهک", ProvinceId = 16 },
            new City { Id = 651, CityName = "بمپور", ProvinceId = 16 },
            new City { Id = 652, CityName = "پیشین", ProvinceId = 16 },
            new City { Id = 653, CityName = "گشت", ProvinceId = 16 },
            new City { Id = 654, CityName = "محمد آباد", ProvinceId = 16 },
            new City { Id = 655, CityName = "زاهدان", ProvinceId = 16 },
            new City { Id = 656, CityName = "", ProvinceId = 16 },
            new City { Id = 657, CityName = "زابلی", ProvinceId = 16 },
            new City { Id = 658, CityName = "چابهار", ProvinceId = 16 },
            new City { Id = 659, CityName = "زراباد", ProvinceId = 16 },
            new City { Id = 660, CityName = "بزمان", ProvinceId = 16 },
            new City { Id = 661, CityName = "اسپکه", ProvinceId = 16 },
            new City { Id = 662, CityName = "فنوچ", ProvinceId = 16 },
            new City { Id = 663, CityName = "سراوان", ProvinceId = 16 },
            new City { Id = 664, CityName = "ادیمی", ProvinceId = 16 },
            new City { Id = 665, CityName = "زابل", ProvinceId = 16 },
            new City { Id = 666, CityName = "دوشت محمد", ProvinceId = 16 },
            new City { Id = 667, CityName = "ایرانشهر", ProvinceId = 16 },
            new City { Id = 668, CityName = "سرباز", ProvinceId = 16 },
            new City { Id = 669, CityName = "سیرکان", ProvinceId = 16 },
            new City { Id = 670, CityName = "میرجاوه", ProvinceId = 16 },
            new City { Id = 671, CityName = "نصرت آباد", ProvinceId = 16 },
            new City { Id = 672, CityName = "سوران", ProvinceId = 16 },
            new City { Id = 673, CityName = "خاش", ProvinceId = 16 },
            new City { Id = 674, CityName = "کنارک", ProvinceId = 16 },
            new City { Id = 675, CityName = "محمدان", ProvinceId = 16 },
            new City { Id = 676, CityName = "نیک شهر", ProvinceId = 16 },
            new City { Id = 677, CityName = "کازرون", ProvinceId = 17 },
            new City { Id = 678, CityName = "کارزین(فتح اباد)", ProvinceId = 17 },
            new City { Id = 679, CityName = "فدامی", ProvinceId = 17 },
            new City { Id = 680, CityName = "خومه زار", ProvinceId = 17 },
            new City { Id = 681, CityName = "سلطان شهر", ProvinceId = 17 },
            new City { Id = 682, CityName = "فیروز آباد", ProvinceId = 17 },
            new City { Id = 683, CityName = "دبیران", ProvinceId = 17 },
            new City { Id = 684, CityName = "باب انار", ProvinceId = 17 },
            new City { Id = 685, CityName = "رامجرد", ProvinceId = 17 },
            new City { Id = 686, CityName = "سروستان", ProvinceId = 17 },
            new City { Id = 687, CityName = "قره بلاغ", ProvinceId = 17 },
            new City { Id = 688, CityName = "ارسنجان", ProvinceId = 17 },
            new City { Id = 689, CityName = "دژکرد", ProvinceId = 17 },
            new City { Id = 690, CityName = "بیرم", ProvinceId = 17 },
            new City { Id = 691, CityName = "دهرم", ProvinceId = 17 },
            new City { Id = 692, CityName = "شیراز", ProvinceId = 17 },
            new City { Id = 693, CityName = "ایزدخواست", ProvinceId = 17 },
            new City { Id = 694, CityName = "علامرودشت", ProvinceId = 17 },
            new City { Id = 695, CityName = "اوز", ProvinceId = 17 },
            new City { Id = 696, CityName = "وراوی", ProvinceId = 17 },
            new City { Id = 697, CityName = "بیضا", ProvinceId = 17 },
            new City { Id = 698, CityName = "نیریز", ProvinceId = 17 },
            new City { Id = 699, CityName = "کنار تخته", ProvinceId = 17 },
            new City { Id = 700, CityName = "امام شهر", ProvinceId = 17 },
            new City { Id = 701, CityName = "جهرم", ProvinceId = 17 },
            new City { Id = 702, CityName = "بابا منیر", ProvinceId = 17 },
            new City { Id = 703, CityName = "گراش", ProvinceId = 17 },
            new City { Id = 704, CityName = "فسا", ProvinceId = 17 },
            new City { Id = 705, CityName = "شهر پیر", ProvinceId = 17 },
            new City { Id = 706, CityName = "حسن آباد", ProvinceId = 17 },
            new City { Id = 707, CityName = "کامفیروز", ProvinceId = 17 },
            new City { Id = 708, CityName = "خنج", ProvinceId = 17 },
            new City { Id = 709, CityName = "خانه زنیان", ProvinceId = 17 },
            new City { Id = 710, CityName = "استهبان", ProvinceId = 17 },
            new City { Id = 711, CityName = "بوانات", ProvinceId = 17 },
            new City { Id = 712, CityName = "لطیفی", ProvinceId = 17 },
            new City { Id = 713, CityName = "فراشبند", ProvinceId = 17 },
            new City { Id = 714, CityName = "زرقان", ProvinceId = 17 },
            new City { Id = 715, CityName = "صغاد", ProvinceId = 17 },
            new City { Id = 716, CityName = "اشکنان", ProvinceId = 17 },
            new City { Id = 717, CityName = "قایمیه", ProvinceId = 17 },
            new City { Id = 718, CityName = "گله دار", ProvinceId = 17 },
            new City { Id = 719, CityName = "دوبرجی", ProvinceId = 17 },
            new City { Id = 720, CityName = "آباده طشک", ProvinceId = 17 },
            new City { Id = 721, CityName = "خرامه", ProvinceId = 17 },
            new City { Id = 722, CityName = "میمند", ProvinceId = 17 },
            new City { Id = 723, CityName = "افزر", ProvinceId = 17 },
            new City { Id = 724, CityName = "دوزه", ProvinceId = 17 },
            new City { Id = 725, CityName = "سیدان", ProvinceId = 17 },
            new City { Id = 726, CityName = "کوپن", ProvinceId = 17 },
            new City { Id = 727, CityName = "زاهدشهر", ProvinceId = 17 },
            new City { Id = 728, CityName = "قادر آباد", ProvinceId = 17 },
            new City { Id = 729, CityName = "سده", ProvinceId = 17 },
            new City { Id = 730, CityName = "بنارویه", ProvinceId = 17 },
            new City { Id = 731, CityName = "سعادت شهر", ProvinceId = 17 },
            new City { Id = 732, CityName = "شهر صدرا", ProvinceId = 17 },
            new City { Id = 733, CityName = "سورمق", ProvinceId = 17 },
            new City { Id = 734, CityName = "حسامی", ProvinceId = 17 },
            new City { Id = 735, CityName = "جویم", ProvinceId = 17 },
            new City { Id = 736, CityName = "خوزی", ProvinceId = 17 },
            new City { Id = 737, CityName = "اردکان", ProvinceId = 17 },
            new City { Id = 738, CityName = "قطرویه", ProvinceId = 17 },
            new City { Id = 739, CityName = "نودان", ProvinceId = 17 },
            new City { Id = 740, CityName = "مبارک آباد دیز", ProvinceId = 17 },
            new City { Id = 741, CityName = "داراب", ProvinceId = 17 },
            new City { Id = 742, CityName = "نور آباد", ProvinceId = 17 },
            new City { Id = 743, CityName = "کوار", ProvinceId = 17 },
            new City { Id = 744, CityName = "نوبندگان", ProvinceId = 17 },
            new City { Id = 745, CityName = "حاجی آباد", ProvinceId = 17 },
            new City { Id = 746, CityName = "خاوران", ProvinceId = 17 },
            new City { Id = 747, CityName = "مرودشت", ProvinceId = 17 },
            new City { Id = 748, CityName = "کوهنجان", ProvinceId = 17 },
            new City { Id = 749, CityName = "ششده", ProvinceId = 17 },
            new City { Id = 750, CityName = "مزایجان", ProvinceId = 17 },
            new City { Id = 751, CityName = "ایج", ProvinceId = 17 },
            new City { Id = 752, CityName = "خور", ProvinceId = 17 },
            new City { Id = 753, CityName = "نوجین", ProvinceId = 17 },
            new City { Id = 754, CityName = "لپویی", ProvinceId = 17 },
            new City { Id = 755, CityName = "بهمن", ProvinceId = 17 },
            new City { Id = 756, CityName = "اهل", ProvinceId = 17 },
            new City { Id = 757, CityName = "خشت", ProvinceId = 17 },
            new City { Id = 758, CityName = "مهر", ProvinceId = 17 },
            new City { Id = 759, CityName = "جنت شهر", ProvinceId = 17 },
            new City { Id = 760, CityName = "مشکان", ProvinceId = 17 },
            new City { Id = 761, CityName = "بالاده", ProvinceId = 17 },
            new City { Id = 762, CityName = "قیر", ProvinceId = 17 },
            new City { Id = 763, CityName = "قطب آباد", ProvinceId = 17 },
            new City { Id = 764, CityName = "خانیمن", ProvinceId = 17 },
            new City { Id = 765, CityName = "مصیری", ProvinceId = 17 },
            new City { Id = 766, CityName = "میانشهر", ProvinceId = 17 },
            new City { Id = 767, CityName = "صفاشهر", ProvinceId = 17 },
            new City { Id = 768, CityName = "اقلید", ProvinceId = 17 },
            new City { Id = 769, CityName = "عمادده", ProvinceId = 17 },
            new City { Id = 770, CityName = "مادر سلیمان", ProvinceId = 17 },
            new City { Id = 771, CityName = "داریان", ProvinceId = 17 },
            new City { Id = 772, CityName = "رونیز", ProvinceId = 17 },
            new City { Id = 773, CityName = "کره ای", ProvinceId = 17 },
            new City { Id = 774, CityName = "لار", ProvinceId = 17 },
            new City { Id = 775, CityName = "اسیر", ProvinceId = 17 },
            new City { Id = 776, CityName = "هماشهر", ProvinceId = 17 },
            new City { Id = 777, CityName = "آباده", ProvinceId = 17 },
            new City { Id = 778, CityName = "لامرد", ProvinceId = 17 },
            new City { Id = 779, CityName = "سگز آباد", ProvinceId = 18 },
            new City { Id = 780, CityName = "بیدستان", ProvinceId = 18 },
            new City { Id = 781, CityName = "کوهین", ProvinceId = 18 },
            new City { Id = 782, CityName = "رازمیان", ProvinceId = 18 },
            new City { Id = 783, CityName = "خرمدشت", ProvinceId = 18 },
            new City { Id = 784, CityName = "آبگرم", ProvinceId = 18 },
            new City { Id = 785, CityName = "شال", ProvinceId = 18 },
            new City { Id = 786, CityName = "شریفیه", ProvinceId = 18 },
            new City { Id = 787, CityName = "اقبالیه", ProvinceId = 18 },
            new City { Id = 788, CityName = "نرجه", ProvinceId = 18 },
            new City { Id = 789, CityName = "ارداق", ProvinceId = 18 },
            new City { Id = 790, CityName = "الوند", ProvinceId = 18 },
            new City { Id = 791, CityName = "خاکعلی", ProvinceId = 18 },
            new City { Id = 792, CityName = "سیردان", ProvinceId = 18 },
            new City { Id = 793, CityName = "ضیاد آباد", ProvinceId = 18 },
            new City { Id = 794, CityName = "بویین زهرا", ProvinceId = 18 },
            new City { Id = 795, CityName = "محمدیه", ProvinceId = 18 },
            new City { Id = 796, CityName = "محمود آباد نمونه", ProvinceId = 18 },
            new City { Id = 797, CityName = "معلم کلایه", ProvinceId = 18 },
            new City { Id = 798, CityName = "اسفرورین", ProvinceId = 18 },
            new City { Id = 799, CityName = "آوج", ProvinceId = 18 },
            new City { Id = 800, CityName = "دانسفهان", ProvinceId = 18 },
            new City { Id = 801, CityName = "آبیک", ProvinceId = 18 },
            new City { Id = 802, CityName = "قزوین", ProvinceId = 18 },
            new City { Id = 803, CityName = "تاکستان", ProvinceId = 18 },
            new City { Id = 804, CityName = "کهک", ProvinceId = 19 },
            new City { Id = 805, CityName = "قم", ProvinceId = 19 },
            new City { Id = 806, CityName = "سلفچگان", ProvinceId = 19 },
            new City { Id = 807, CityName = "جعفریه", ProvinceId = 19 },
            new City { Id = 808, CityName = "قنوات", ProvinceId = 19 },
            new City { Id = 809, CityName = "دستجرد", ProvinceId = 19 },
            new City { Id = 810, CityName = "توپ آغاج", ProvinceId = 20 },
            new City { Id = 811, CityName = "سرو آباد", ProvinceId = 20 },
            new City { Id = 812, CityName = "بویین سفلی", ProvinceId = 20 },
            new City { Id = 813, CityName = "زرینه", ProvinceId = 20 },
            new City { Id = 814, CityName = "دلبران", ProvinceId = 20 },
            new City { Id = 815, CityName = "سنندج", ProvinceId = 20 },
            new City { Id = 816, CityName = "یاسوکند", ProvinceId = 20 },
            new City { Id = 817, CityName = "موچش", ProvinceId = 20 },
            new City { Id = 818, CityName = "بانه", ProvinceId = 20 },
            new City { Id = 819, CityName = "مریوان", ProvinceId = 20 },
            new City { Id = 820, CityName = "سریش آباد", ProvinceId = 20 },
            new City { Id = 821, CityName = "صاحب", ProvinceId = 20 },
            new City { Id = 822, CityName = "دهگلان", ProvinceId = 20 },
            new City { Id = 823, CityName = "بابارشانی", ProvinceId = 20 },
            new City { Id = 824, CityName = "دیواندره", ProvinceId = 20 },
            new City { Id = 825, CityName = "برده رشه", ProvinceId = 20 },
            new City { Id = 826, CityName = "شویشه", ProvinceId = 20 },
            new City { Id = 827, CityName = "بیجار", ProvinceId = 20 },
            new City { Id = 828, CityName = "اورامان تخت", ProvinceId = 20 },
            new City { Id = 829, CityName = "کانی سور", ProvinceId = 20 },
            new City { Id = 830, CityName = "کانی دینار", ProvinceId = 20 },
            new City { Id = 831, CityName = "دزج", ProvinceId = 20 },
            new City { Id = 832, CityName = "سقز", ProvinceId = 20 },
            new City { Id = 833, CityName = "بلبان آباد", ProvinceId = 20 },
            new City { Id = 834, CityName = "پیرتاج", ProvinceId = 20 },
            new City { Id = 835, CityName = "کامیاران", ProvinceId = 20 },
            new City { Id = 836, CityName = "آرمرده", ProvinceId = 20 },
            new City { Id = 837, CityName = "چناره", ProvinceId = 20 },
            new City { Id = 838, CityName = "کهنوج", ProvinceId = 21 },
            new City { Id = 839, CityName = "بلوک", ProvinceId = 21 },
            new City { Id = 840, CityName = "پاریز", ProvinceId = 21 },
            new City { Id = 841, CityName = "گنبکی", ProvinceId = 21 },
            new City { Id = 842, CityName = "زنگی آباد", ProvinceId = 21 },
            new City { Id = 843, CityName = "بم", ProvinceId = 21 },
            new City { Id = 844, CityName = "خانوک", ProvinceId = 21 },
            new City { Id = 845, CityName = "کیانشهر", ProvinceId = 21 },
            new City { Id = 846, CityName = "جوپار", ProvinceId = 21 },
            new City { Id = 847, CityName = "عنبرآباد", ProvinceId = 21 },
            new City { Id = 848, CityName = "جوزم", ProvinceId = 21 },
            new City { Id = 849, CityName = "نظام شهر", ProvinceId = 21 },
            new City { Id = 850, CityName = "لاله زار", ProvinceId = 21 },
            new City { Id = 851, CityName = "کشکوییه", ProvinceId = 21 },
            new City { Id = 852, CityName = "زید آباد", ProvinceId = 21 },
            new City { Id = 853, CityName = "هنزا", ProvinceId = 21 },
            new City { Id = 854, CityName = "چترود", ProvinceId = 21 },
            new City { Id = 855, CityName = "جبالبارز", ProvinceId = 21 },
            new City { Id = 856, CityName = "سیرجان", ProvinceId = 21 },
            new City { Id = 857, CityName = "رودبار", ProvinceId = 21 },
            new City { Id = 858, CityName = "کرمان", ProvinceId = 21 },
            new City { Id = 859, CityName = "بافت", ProvinceId = 21 },
            new City { Id = 860, CityName = "صفاییه", ProvinceId = 21 },
            new City { Id = 861, CityName = "منوجان", ProvinceId = 21 },
            new City { Id = 862, CityName = "اندوهجرد", ProvinceId = 21 },
            new City { Id = 863, CityName = "هجدک", ProvinceId = 21 },
            new City { Id = 864, CityName = "خورسند", ProvinceId = 21 },
            new City { Id = 865, CityName = "امین شهر", ProvinceId = 21 },
            new City { Id = 866, CityName = "بردسیر", ProvinceId = 21 },
            new City { Id = 867, CityName = "رفسنجان", ProvinceId = 21 },
            new City { Id = 868, CityName = "هما شهر", ProvinceId = 21 },
            new City { Id = 869, CityName = "محمد آباد", ProvinceId = 21 },
            new City { Id = 870, CityName = "اختیار آباد", ProvinceId = 21 },
            new City { Id = 871, CityName = "بروات", ProvinceId = 21 },
            new City { Id = 872, CityName = "ریحان", ProvinceId = 21 },
            new City { Id = 873, CityName = "کوهبنان", ProvinceId = 21 },
            new City { Id = 874, CityName = "ماهان", ProvinceId = 21 },
            new City { Id = 875, CityName = "دوساری", ProvinceId = 21 },
            new City { Id = 876, CityName = "دهج", ProvinceId = 21 },
            new City { Id = 877, CityName = "فاریاب", ProvinceId = 21 },
            new City { Id = 878, CityName = "گلزار", ProvinceId = 21 },
            new City { Id = 879, CityName = "بهرمان", ProvinceId = 21 },
            new City { Id = 880, CityName = "بلورد", ProvinceId = 21 },
            new City { Id = 881, CityName = "فهرج", ProvinceId = 21 },
            new City { Id = 882, CityName = "کاظم آباد", ProvinceId = 21 },
            new City { Id = 883, CityName = "جیرفت", ProvinceId = 21 },
            new City { Id = 884, CityName = "نجف شهر", ProvinceId = 21 },
            new City { Id = 885, CityName = "قلعه گنج", ProvinceId = 21 },
            new City { Id = 886, CityName = "باغین", ProvinceId = 21 },
            new City { Id = 887, CityName = "بزنجان", ProvinceId = 21 },
            new City { Id = 888, CityName = "زرند", ProvinceId = 21 },
            new City { Id = 889, CityName = "نودژ", ProvinceId = 21 },
            new City { Id = 890, CityName = "گلباف", ProvinceId = 21 },
            new City { Id = 891, CityName = "راور", ProvinceId = 21 },
            new City { Id = 892, CityName = "خاتون آباد", ProvinceId = 21 },
            new City { Id = 893, CityName = "نرماشیر", ProvinceId = 21 },
            new City { Id = 894, CityName = "دشتکار", ProvinceId = 21 },
            new City { Id = 895, CityName = "مس سرچشمه", ProvinceId = 21 },
            new City { Id = 896, CityName = "خواجو شهر", ProvinceId = 21 },
            new City { Id = 897, CityName = "رابر", ProvinceId = 21 },
            new City { Id = 898, CityName = "راین", ProvinceId = 21 },
            new City { Id = 899, CityName = "درب بهشت", ProvinceId = 21 },
            new City { Id = 900, CityName = "یزدان شهر", ProvinceId = 21 },
            new City { Id = 901, CityName = "زهکلوت", ProvinceId = 21 },
            new City { Id = 902, CityName = "محی آباد", ProvinceId = 21 },
            new City { Id = 903, CityName = "مردهک", ProvinceId = 21 },
            new City { Id = 904, CityName = "شهداد", ProvinceId = 21 },
            new City { Id = 905, CityName = "ارزوییه", ProvinceId = 21 },
            new City { Id = 906, CityName = "نگار", ProvinceId = 21 },
            new City { Id = 907, CityName = "شهر بابک", ProvinceId = 21 },
            new City { Id = 908, CityName = "انار", ProvinceId = 21 },
            new City { Id = 909, CityName = "سنقر", ProvinceId = 22 },
            new City { Id = 910, CityName = "شاهو", ProvinceId = 22 },
            new City { Id = 911, CityName = "بانوره", ProvinceId = 22 },
            new City { Id = 912, CityName = "تازه آباد", ProvinceId = 22 },
            new City { Id = 913, CityName = "هلشی", ProvinceId = 22 },
            new City { Id = 914, CityName = "جوانرود", ProvinceId = 22 },
            new City { Id = 915, CityName = "قصرشیرین", ProvinceId = 22 },
            new City { Id = 916, CityName = "نوسود", ProvinceId = 22 },
            new City { Id = 917, CityName = "کرند", ProvinceId = 22 },
            new City { Id = 918, CityName = "کوزران", ProvinceId = 22 },
            new City { Id = 919, CityName = "بیستون", ProvinceId = 22 },
            new City { Id = 920, CityName = "حمیل", ProvinceId = 22 },
            new City { Id = 921, CityName = "گیلانغرب", ProvinceId = 22 },
            new City { Id = 922, CityName = "سطر", ProvinceId = 22 },
            new City { Id = 923, CityName = "روانسر", ProvinceId = 22 },
            new City { Id = 924, CityName = "پاوه", ProvinceId = 22 },
            new City { Id = 925, CityName = "ازگله", ProvinceId = 22 },
            new City { Id = 926, CityName = "کرمانشاه", ProvinceId = 22 },
            new City { Id = 927, CityName = "میان راهان", ProvinceId = 22 },
            new City { Id = 928, CityName = "کنگاور", ProvinceId = 22 },
            new City { Id = 929, CityName = "سرپل ذهاب", ProvinceId = 22 },
            new City { Id = 930, CityName = "ریجاب", ProvinceId = 22 },
            new City { Id = 931, CityName = "باینگان", ProvinceId = 22 },
            new City { Id = 932, CityName = "هرسین", ProvinceId = 22 },
            new City { Id = 933, CityName = "اسلام آباد غرب", ProvinceId = 22 },
            new City { Id = 934, CityName = "سرمست", ProvinceId = 22 },
            new City { Id = 935, CityName = "سومار", ProvinceId = 22 },
            new City { Id = 936, CityName = "نودشه", ProvinceId = 22 },
            new City { Id = 937, CityName = "گهواره", ProvinceId = 22 },
            new City { Id = 938, CityName = "رباط", ProvinceId = 22 },
            new City { Id = 939, CityName = "صحنه", ProvinceId = 22 },
            new City { Id = 940, CityName = "گودین", ProvinceId = 22 },
            new City { Id = 941, CityName = "گراب سفلی", ProvinceId = 23 },
            new City { Id = 942, CityName = "لنده", ProvinceId = 23 },
            new City { Id = 943, CityName = "سی سخت", ProvinceId = 23 },
            new City { Id = 944, CityName = "دهدشت", ProvinceId = 23 },
            new City { Id = 945, CityName = "یاسوج", ProvinceId = 23 },
            new City { Id = 946, CityName = "سرفاریاب", ProvinceId = 23 },
            new City { Id = 947, CityName = "دوگنبدان", ProvinceId = 23 },
            new City { Id = 948, CityName = "چیتاب", ProvinceId = 23 },
            new City { Id = 949, CityName = "لیکک", ProvinceId = 23 },
            new City { Id = 950, CityName = "دیشموک", ProvinceId = 23 },
            new City { Id = 951, CityName = "مادوان", ProvinceId = 23 },
            new City { Id = 952, CityName = "باشت", ProvinceId = 23 },
            new City { Id = 953, CityName = "پاتاوه", ProvinceId = 23 },
            new City { Id = 954, CityName = "قلعه رییسی", ProvinceId = 23 },
            new City { Id = 955, CityName = "مارگون", ProvinceId = 23 },
            new City { Id = 956, CityName = "چرام", ProvinceId = 23 },
            new City { Id = 957, CityName = "سوق", ProvinceId = 23 },
            new City { Id = 958, CityName = "سیمین شهر", ProvinceId = 24 },
            new City { Id = 959, CityName = "مزرعه", ProvinceId = 24 },
            new City { Id = 960, CityName = "رامیان", ProvinceId = 24 },
            new City { Id = 961, CityName = "فراغی", ProvinceId = 24 },
            new City { Id = 962, CityName = "گنبد کاووس", ProvinceId = 24 },
            new City { Id = 963, CityName = "کردکوی", ProvinceId = 24 },
            new City { Id = 964, CityName = "مراوه", ProvinceId = 24 },
            new City { Id = 965, CityName = "بندر ترکمن", ProvinceId = 24 },
            new City { Id = 966, CityName = "نگین شهر", ProvinceId = 24 },
            new City { Id = 967, CityName = "آق قلا", ProvinceId = 24 },
            new City { Id = 968, CityName = "سرخنکلاته", ProvinceId = 24 },
            new City { Id = 969, CityName = "گلیکش", ProvinceId = 24 },
            new City { Id = 970, CityName = "سنگدوین", ProvinceId = 24 },
            new City { Id = 971, CityName = "دلند", ProvinceId = 24 },
            new City { Id = 972, CityName = "بندر گز", ProvinceId = 24 },
            new City { Id = 973, CityName = "نوده خاندوز", ProvinceId = 24 },
            new City { Id = 974, CityName = "مینودشت", ProvinceId = 24 },
            new City { Id = 975, CityName = "گرگان", ProvinceId = 24 },
            new City { Id = 976, CityName = "گمیش تپه", ProvinceId = 24 },
            new City { Id = 977, CityName = "علی آباد", ProvinceId = 24 },
            new City { Id = 978, CityName = "خان ببین", ProvinceId = 24 },
            new City { Id = 979, CityName = "کلاله", ProvinceId = 24 },
            new City { Id = 980, CityName = "اینچه برون", ProvinceId = 24 },
            new City { Id = 981, CityName = "فاضل آباد", ProvinceId = 24 },
            new City { Id = 982, CityName = "تاتار علیا", ProvinceId = 24 },
            new City { Id = 983, CityName = "نو کنده", ProvinceId = 24 },
            new City { Id = 984, CityName = "آزادشهر", ProvinceId = 24 },
            new City { Id = 985, CityName = "انبار آلوم", ProvinceId = 24 },
            new City { Id = 986, CityName = "جلین", ProvinceId = 24 },
            new City { Id = 987, CityName = "منجیل", ProvinceId = 25 },
            new City { Id = 988, CityName = "شلمان", ProvinceId = 25 },
            new City { Id = 989, CityName = "خشکبیجار", ProvinceId = 25 },
            new City { Id = 990, CityName = "ماکلوان", ProvinceId = 25 },
            new City { Id = 991, CityName = "سنگر", ProvinceId = 25 },
            new City { Id = 992, CityName = "مرجقل", ProvinceId = 25 },
            new City { Id = 993, CityName = "لیسار", ProvinceId = 25 },
            new City { Id = 994, CityName = "رضوانشهر", ProvinceId = 25 },
            new City { Id = 995, CityName = "رحیم آباد", ProvinceId = 25 },
            new City { Id = 996, CityName = "لوندویل", ProvinceId = 25 },
            new City { Id = 997, CityName = "احمد سرگوراب", ProvinceId = 25 },
            new City { Id = 998, CityName = "لوشان", ProvinceId = 25 },
            new City { Id = 999, CityName = "اطاقور", ProvinceId = 25 },
            new City { Id = 1001, CityName = "لشت نشاء", ProvinceId = 25 },
            new City { Id = 1002, CityName = "فومن", ProvinceId = 25 },
            new City { Id = 1003, CityName = "چوبر", ProvinceId = 25 },
            new City { Id = 1004, CityName = "بازار جمعه", ProvinceId = 25 },
            new City { Id = 1005, CityName = "کلاچای", ProvinceId = 25 },
            new City { Id = 1006, CityName = "بندر انزلی", ProvinceId = 25 },
            new City { Id = 1007, CityName = "املش", ProvinceId = 25 },
            new City { Id = 1008, CityName = "رستم آباد", ProvinceId = 25 },
            new City { Id = 1009, CityName = "لاهیجان", ProvinceId = 25 },
            new City { Id = 1010, CityName = "توتکابن", ProvinceId = 25 },
            new City { Id = 1011, CityName = "لنگرود", ProvinceId = 25 },
            new City { Id = 1012, CityName = "کوچصفهان", ProvinceId = 25 },
            new City { Id = 1013, CityName = "صومعه سرا", ProvinceId = 25 },
            new City { Id = 1014, CityName = "اسالم", ProvinceId = 25 },
            new City { Id = 1015, CityName = "دیلمان", ProvinceId = 25 },
            new City { Id = 1016, CityName = "رودسر", ProvinceId = 25 },
            new City { Id = 1017, CityName = "کیاشهر", ProvinceId = 25 },
            new City { Id = 1018, CityName = "شفت", ProvinceId = 25 },
            new City { Id = 1019, CityName = "رودبار", ProvinceId = 25 },
            new City { Id = 1020, CityName = "کومله", ProvinceId = 25 },
            new City { Id = 1021, CityName = "رشت", ProvinceId = 25 },
            new City { Id = 1022, CityName = "ماسوله", ProvinceId = 25 },
            new City { Id = 1023, CityName = "خمام", ProvinceId = 25 },
            new City { Id = 1024, CityName = "ماسال", ProvinceId = 25 },
            new City { Id = 1025, CityName = "واجارگاه", ProvinceId = 25 },
            new City { Id = 1026, CityName = "هشتپر (تالش)", ProvinceId = 25 },
            new City { Id = 1027, CityName = "پره سر", ProvinceId = 25 },
            new City { Id = 1028, CityName = "بره سر", ProvinceId = 25 },
            new City { Id = 1029, CityName = "آستارا", ProvinceId = 25 },
            new City { Id = 1030, CityName = "رودبنه", ProvinceId = 25 },
            new City { Id = 1031, CityName = "جیرنده", ProvinceId = 25 },
            new City { Id = 1032, CityName = "چاف و چمخاله", ProvinceId = 25 },
            new City { Id = 1033, CityName = "لولمان", ProvinceId = 25 },
            new City { Id = 1034, CityName = "گوراب زرمیخ", ProvinceId = 25 },
            new City { Id = 1035, CityName = "حویق", ProvinceId = 25 },
            new City { Id = 1036, CityName = "سیاهکل", ProvinceId = 25 },
            new City { Id = 1037, CityName = "چابکسر", ProvinceId = 25 },
            new City { Id = 1038, CityName = "آستانه اشرفیه", ProvinceId = 25 },
            new City { Id = 1039, CityName = "رانکوه", ProvinceId = 25 },
            new City { Id = 1040, CityName = "چلانچولان", ProvinceId = 26 },
            new City { Id = 1041, CityName = "بیران شهر", ProvinceId = 26 },
            new City { Id = 1042, CityName = "ویسیان", ProvinceId = 26 },
            new City { Id = 1043, CityName = "ساری", ProvinceId = 27 },
new City { Id = 1044, CityName = "بابل", ProvinceId = 27 },
new City { Id = 1045, CityName = "آمل", ProvinceId = 27 },
new City { Id = 1046, CityName = "قائم‌شهر", ProvinceId = 27 },
new City { Id = 1047, CityName = "نوشهر", ProvinceId = 27 },
new City { Id = 1048, CityName = "چالوس", ProvinceId = 27 },
new City { Id = 1049, CityName = "تنکابن", ProvinceId = 27 },
new City { Id = 1050, CityName = "رامسر", ProvinceId = 27 },
new City { Id = 1051, CityName = "اراک", ProvinceId = 28 },
new City { Id = 1052, CityName = "ساوه", ProvinceId = 28 },
new City { Id = 1053, CityName = "خمین", ProvinceId = 28 },
new City { Id = 1054, CityName = "محلات", ProvinceId = 28 },
new City { Id = 1055, CityName = "دلیجان", ProvinceId = 28 },
new City { Id = 1056, CityName = "تفرش", ProvinceId = 28 },
new City { Id = 1057, CityName = "شازند", ProvinceId = 28 },
new City { Id = 1058, CityName = "آشتیان", ProvinceId = 28 },
new City { Id = 1059, CityName = "بندرعباس", ProvinceId = 29 },
new City { Id = 1060, CityName = "قشم", ProvinceId = 29 },
new City { Id = 1061, CityName = "کیش", ProvinceId = 29 },
new City { Id = 1062, CityName = "بندر لنگه", ProvinceId = 29 },
new City { Id = 1063, CityName = "میناب", ProvinceId = 29 },
new City { Id = 1064, CityName = "رودان", ProvinceId = 29 },
new City { Id = 1065, CityName = "جاسک", ProvinceId = 29 },
new City { Id = 1066, CityName = "بستک", ProvinceId = 29 },
new City { Id = 1067, CityName = "همدان", ProvinceId = 30 },
new City { Id = 1068, CityName = "ملایر", ProvinceId = 30 },
new City { Id = 1069, CityName = "نهاوند", ProvinceId = 30 },
new City { Id = 1070, CityName = "تویسرکان", ProvinceId = 30 },
new City { Id = 1071, CityName = "کبودرآهنگ", ProvinceId = 30 },
new City { Id = 1072, CityName = "رزن", ProvinceId = 30 },
new City { Id = 1073, CityName = "بهار", ProvinceId = 30 },
new City { Id = 1074, CityName = "اسدآباد", ProvinceId = 30 },
new City { Id = 1075, CityName = "یزد", ProvinceId = 31 },
new City { Id = 1076, CityName = "میبد", ProvinceId = 31 },
new City { Id = 1077, CityName = "اردکان", ProvinceId = 31 },
new City { Id = 1078, CityName = "بافق", ProvinceId = 31 },
new City { Id = 1079, CityName = "مهریز", ProvinceId = 31 },
new City { Id = 1080, CityName = "تفت", ProvinceId = 31 },
new City { Id = 1081, CityName = "ابرکوه", ProvinceId = 31 },
new City { Id = 1082, CityName = "اشکذر", ProvinceId = 31 }

            );
    }
}
